package com.warbler.feature.weather.ui.main

data class WeatherUiState(
    val locationName: String,
    val temperature: String,
    val description: String,
    val dateTitle: String,
    val feelsLike: String,
    val hasAqi: Boolean,
    val aqiValue: String,
    val aqiLevel: Int = 0,
    val hasAlerts: Boolean,
    val alertTitle: String = "",
    val alertDescription: String = "",
    val iconRes: Int,
    val wind: String = "",
    val windUnit: String = "",
    val humidity: String = "",
    val rain: String = "",
    val accumulationUnit: String = "",
    val hourlyForecasts: List<HourlyForecastItem> = emptyList(),
    val dailyForecasts: List<DailyForecastItem> = emptyList(),
    val uvIndex: String = "",
    val pressure: String = "",
    val visibility: String = "",
    val clouds: String = "",
    val dewPoint: String = "",
    val sunrise: String = "",
    val sunset: String = "",
    val moonrise: String = "",
    val moonset: String = "",
    val moonPhase: Double = 0.0,
    val moonPhaseName: String = "",
    val moonIllumination: String = "",
    val windDeg: Int = 0,
    val aqiComponents: Map<String, Double>? = null,
    val isOffline: Boolean = false,
    val lastRefreshedAt: String? = null,
)

data class HourlyForecastItem(
    val time: String,
    val temperature: String,
    val iconRes: Int,
    val pop: Float = 0f,
    val accumulation: Float = 0f,
    val rainAccumulation: Float = 0f,
    val snowAccumulation: Float = 0f,
    val humidity: Int = 0,
    val windSpeed: Float = 0f,
    val windGust: Float = 0f,
    val uvi: Float = 0f,
)

data class DailyForecastItem(
    val day: String,
    val dateTitle: String = "",
    val highTemp: Int,
    val lowTemp: Int,
    val iconRes: Int,
    val description: String = "",
    val sunrise: String = "",
    val sunset: String = "",
    val moonrise: String = "",
    val moonset: String = "",
    val humidity: String = "",
    val wind: String = "",
    val pop: String = "",
    val uvIndex: String = "",
    val pressure: String = "",
    val rain: String = "",
    val snow: String = "",
    val clouds: String = "",
    val dewPoint: String = "",
)
